# Generated by Django 3.0.8 on 2020-08-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thumbnailapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Pictures',
        ),
    ]
